import createClient, { Middleware } from "openapi-fetch";
import { myAppUrl } from "~/app";
import type { paths } from "~/types/api-schema"; // generated by openapi-typescript

export const fetchClient = createClient<paths>({
  baseUrl: import.meta.env.VITE_API_URL,
  credentials: "include",
});

const authMiddleware: Middleware = {
  async onResponse({ response }) {
    if (response.status === 401) {
      window.location.href = myAppUrl.login;
    }

    if (!response.ok) {
      const isBodyJSON = response.headers.get("content-type")?.includes("json");
      const body = isBodyJSON
        ? await response.clone().json()
        : await response.clone().text();
      throw new Error(body);
    }

    return undefined;
  },
};

fetchClient.use(authMiddleware);
