/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// biome-ignore-all
/*
 * ------------------------------------------------------------
 * ## This file was automatically generated by drizzle-zero  ##
 * ## Any changes you make to this file will be overwritten. ##
 * ##                                                        ##
 * ## Additionally, you should also exclude this file from   ##
 * ## your linter and/or formatter to prevent it from being  ##
 * ## checked or modified.                                   ##
 * ##                                                        ##
 * ## SOURCE: https://github.com/BriefHQ/drizzle-zero        ##
 * ------------------------------------------------------------
 */

export type Schema = {
  readonly tables: {
    usersTable: {
      name: "usersTable";
      primaryKey: any;
      columns: {
        readonly id: {
          optional: false;
          type: "string";
          customType: string;
        };
        readonly email: {
          optional: false;
          type: "string";
          customType: string;
        };
        readonly name: {
          optional: false;
          type: "string";
          customType: string;
        };
        readonly createdAt: {
          optional: false;
          type: "number";
          customType: number;
          serverName: string;
        };
        readonly updatedAt: {
          optional: false;
          type: "number";
          customType: number;
          serverName: string;
        };
        readonly emailVerified: {
          optional: false;
          type: "boolean";
          customType: boolean;
          serverName: string;
        };
        readonly image: {
          type: "string";
          customType: string;
          optional: true;
        };
      };
    };
    organizationsTable: {
      name: "organizationsTable";
      primaryKey: any;
      columns: {
        readonly id: {
          optional: false;
          type: "string";
          customType: string;
        };
        readonly name: {
          optional: false;
          type: "string";
          customType: string;
        };
        readonly createdAt: {
          optional: false;
          type: "number";
          customType: number;
          serverName: string;
        };
        readonly slug: {
          type: "string";
          customType: string;
          optional: true;
        };
        readonly logo: {
          type: "string";
          customType: string;
          optional: true;
        };
        readonly metadata: {
          type: "string";
          customType: string;
          optional: true;
        };
      };
    };
    membersTable: {
      name: "membersTable";
      primaryKey: any;
      columns: {
        readonly id: {
          optional: false;
          type: "string";
          customType: string;
        };
        readonly createdAt: {
          optional: false;
          type: "number";
          customType: number;
          serverName: string;
        };
        readonly organizationId: {
          optional: false;
          type: "string";
          customType: string;
          serverName: string;
        };
        readonly role: {
          optional: false;
          type: "string";
          customType: string;
        };
        readonly userId: {
          optional: false;
          type: "string";
          customType: string;
          serverName: string;
        };
      };
    };
    boardsTable: {
      name: "boardsTable";
      primaryKey: any;
      columns: {
        readonly id: {
          optional: false;
          type: "string";
          customType: string;
        };
        readonly slug: {
          optional: false;
          type: "string";
          customType: string;
        };
        readonly createdAt: {
          optional: false;
          type: "number";
          customType: number;
        };
        readonly updatedAt: {
          type: "number";
          customType: number;
          optional: true;
        };
        readonly organizationId: {
          type: "string";
          customType: string;
          optional: true;
          serverName: string;
        };
        readonly creatorId: {
          type: "string";
          customType: string;
          optional: true;
          serverName: string;
        };
        readonly name: {
          optional: false;
          type: "string";
          customType: string;
        };
        readonly color: {
          type: "string";
          customType: string;
          optional: true;
        };
        readonly deletedAt: {
          type: "number";
          customType: number;
          optional: true;
        };
      };
    };
    columnsTable: {
      name: "columnsTable";
      primaryKey: any;
      columns: {
        readonly id: {
          optional: false;
          type: "string";
          customType: string;
        };
        readonly boardId: {
          optional: false;
          type: "string";
          customType: string;
        };
        readonly createdAt: {
          optional: false;
          type: "number";
          customType: number;
        };
        readonly updatedAt: {
          type: "number";
          customType: number;
          optional: true;
        };
        readonly deletedAt: {
          type: "number";
          customType: number;
          optional: true;
        };
        readonly name: {
          optional: false;
          type: "string";
          customType: string;
        };
        readonly position: {
          optional: false;
          type: "number";
          customType: number;
        };
        readonly organizationId: {
          type: "string";
          customType: string;
          optional: true;
          serverName: string;
        };
        readonly creatorId: {
          type: "string";
          customType: string;
          optional: true;
          serverName: string;
        };
      };
    };
    tasksTable: {
      name: "tasksTable";
      primaryKey: any;
      columns: {
        readonly id: {
          optional: false;
          type: "string";
          customType: string;
        };
        readonly columnId: {
          optional: false;
          type: "string";
          customType: string;
        };
        readonly createdAt: {
          optional: false;
          type: "number";
          customType: number;
        };
        readonly deletedAt: {
          type: "number";
          customType: number;
          optional: true;
        };
        readonly name: {
          optional: false;
          type: "string";
          customType: string;
        };
        readonly position: {
          optional: false;
          type: "number";
          customType: number;
        };
        readonly updatedAt: {
          type: "number";
          customType: number;
          optional: true;
        };
        readonly organizationId: {
          type: "string";
          customType: string;
          optional: true;
          serverName: string;
        };
        readonly creatorId: {
          type: "string";
          customType: string;
          optional: true;
          serverName: string;
        };
        readonly content: {
          type: "string";
          customType: string;
          optional: true;
        };
        readonly assigneeId: {
          type: "string";
          customType: string;
          optional: true;
        };
      };
    };
    notesTable: {
      name: "notesTable";
      primaryKey: any;
      columns: {
        readonly id: {
          optional: false;
          type: "string";
          customType: string;
        };
        readonly createdAt: {
          optional: false;
          type: "number";
          customType: number;
        };
        readonly updatedAt: {
          type: "number";
          customType: number;
          optional: true;
        };
        readonly organizationId: {
          type: "string";
          customType: string;
          optional: true;
          serverName: string;
        };
        readonly name: {
          optional: false;
          type: "string";
          customType: string;
        };
        readonly content: {
          optional: false;
          type: "string";
          customType: string;
        };
        readonly deletedAt: {
          type: "number";
          customType: number;
          optional: true;
        };
        readonly creatorId: {
          type: "string";
          customType: string;
          optional: true;
          serverName: string;
        };
      };
    };
  };
  readonly relationships: {
    usersTable: {
      columns: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "name"
            | "createdAt"
            | "updatedAt"
            | "organizationId"
            | "creatorId"
            | "deletedAt"
            | "boardId"
            | "position"
          )[];
          readonly destSchema: "columnsTable";
          readonly cardinality: "many";
        },
      ];
      members: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "createdAt"
            | "userId"
            | "organizationId"
            | "role"
          )[];
          readonly destSchema: "membersTable";
          readonly cardinality: "many";
        },
      ];
      boards: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "name"
            | "createdAt"
            | "updatedAt"
            | "slug"
            | "organizationId"
            | "color"
            | "creatorId"
            | "deletedAt"
          )[];
          readonly destSchema: "boardsTable";
          readonly cardinality: "many";
        },
      ];
      tasks: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "name"
            | "createdAt"
            | "updatedAt"
            | "organizationId"
            | "creatorId"
            | "deletedAt"
            | "position"
            | "content"
            | "columnId"
            | "assigneeId"
          )[];
          readonly destSchema: "tasksTable";
          readonly cardinality: "many";
        },
      ];
      notes: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "name"
            | "createdAt"
            | "updatedAt"
            | "organizationId"
            | "creatorId"
            | "deletedAt"
            | "content"
          )[];
          readonly destSchema: "notesTable";
          readonly cardinality: "many";
        },
      ];
      assignedTasks: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "name"
            | "createdAt"
            | "updatedAt"
            | "organizationId"
            | "creatorId"
            | "deletedAt"
            | "position"
            | "content"
            | "columnId"
            | "assigneeId"
          )[];
          readonly destSchema: "tasksTable";
          readonly cardinality: "many";
        },
      ];
    };
    organizationsTable: {
      columns: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "name"
            | "createdAt"
            | "updatedAt"
            | "organizationId"
            | "creatorId"
            | "deletedAt"
            | "boardId"
            | "position"
          )[];
          readonly destSchema: "columnsTable";
          readonly cardinality: "many";
        },
      ];
      members: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "createdAt"
            | "userId"
            | "organizationId"
            | "role"
          )[];
          readonly destSchema: "membersTable";
          readonly cardinality: "many";
        },
      ];
      boards: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "name"
            | "createdAt"
            | "updatedAt"
            | "slug"
            | "organizationId"
            | "color"
            | "creatorId"
            | "deletedAt"
          )[];
          readonly destSchema: "boardsTable";
          readonly cardinality: "many";
        },
      ];
      tasks: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "name"
            | "createdAt"
            | "updatedAt"
            | "organizationId"
            | "creatorId"
            | "deletedAt"
            | "position"
            | "content"
            | "columnId"
            | "assigneeId"
          )[];
          readonly destSchema: "tasksTable";
          readonly cardinality: "many";
        },
      ];
      notes: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "name"
            | "createdAt"
            | "updatedAt"
            | "organizationId"
            | "creatorId"
            | "deletedAt"
            | "content"
          )[];
          readonly destSchema: "notesTable";
          readonly cardinality: "many";
        },
      ];
    } & {
      readonly orgToUsers: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "createdAt"
            | "userId"
            | "organizationId"
            | "role"
          )[];
          readonly destSchema: "membersTable";
          readonly cardinality: "many";
        },
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "name"
            | "email"
            | "emailVerified"
            | "image"
            | "createdAt"
            | "updatedAt"
          )[];
          readonly destSchema: "usersTable";
          readonly cardinality: "many";
        },
      ];
    };
    membersTable: {
      user: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "name"
            | "email"
            | "emailVerified"
            | "image"
            | "createdAt"
            | "updatedAt"
          )[];
          readonly destSchema: "usersTable";
          readonly cardinality: "one";
        },
      ];
      organization: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "name"
            | "createdAt"
            | "slug"
            | "logo"
            | "metadata"
          )[];
          readonly destSchema: "organizationsTable";
          readonly cardinality: "one";
        },
      ];
    };
    boardsTable: {
      columns: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "name"
            | "createdAt"
            | "updatedAt"
            | "organizationId"
            | "creatorId"
            | "deletedAt"
            | "boardId"
            | "position"
          )[];
          readonly destSchema: "columnsTable";
          readonly cardinality: "many";
        },
      ];
      organization: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "name"
            | "createdAt"
            | "slug"
            | "logo"
            | "metadata"
          )[];
          readonly destSchema: "organizationsTable";
          readonly cardinality: "one";
        },
      ];
      creator: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "name"
            | "email"
            | "emailVerified"
            | "image"
            | "createdAt"
            | "updatedAt"
          )[];
          readonly destSchema: "usersTable";
          readonly cardinality: "one";
        },
      ];
    };
    columnsTable: {
      organization: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "name"
            | "createdAt"
            | "slug"
            | "logo"
            | "metadata"
          )[];
          readonly destSchema: "organizationsTable";
          readonly cardinality: "one";
        },
      ];
      tasks: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "name"
            | "createdAt"
            | "updatedAt"
            | "organizationId"
            | "creatorId"
            | "deletedAt"
            | "position"
            | "content"
            | "columnId"
            | "assigneeId"
          )[];
          readonly destSchema: "tasksTable";
          readonly cardinality: "many";
        },
      ];
      creator: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "name"
            | "email"
            | "emailVerified"
            | "image"
            | "createdAt"
            | "updatedAt"
          )[];
          readonly destSchema: "usersTable";
          readonly cardinality: "one";
        },
      ];
      board: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "name"
            | "createdAt"
            | "updatedAt"
            | "slug"
            | "organizationId"
            | "color"
            | "creatorId"
            | "deletedAt"
          )[];
          readonly destSchema: "boardsTable";
          readonly cardinality: "one";
        },
      ];
    };
    tasksTable: {
      organization: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "name"
            | "createdAt"
            | "slug"
            | "logo"
            | "metadata"
          )[];
          readonly destSchema: "organizationsTable";
          readonly cardinality: "one";
        },
      ];
      creator: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "name"
            | "email"
            | "emailVerified"
            | "image"
            | "createdAt"
            | "updatedAt"
          )[];
          readonly destSchema: "usersTable";
          readonly cardinality: "one";
        },
      ];
      column: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "name"
            | "createdAt"
            | "updatedAt"
            | "organizationId"
            | "creatorId"
            | "deletedAt"
            | "boardId"
            | "position"
          )[];
          readonly destSchema: "columnsTable";
          readonly cardinality: "one";
        },
      ];
      assignee: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "name"
            | "email"
            | "emailVerified"
            | "image"
            | "createdAt"
            | "updatedAt"
          )[];
          readonly destSchema: "usersTable";
          readonly cardinality: "one";
        },
      ];
    };
    notesTable: {
      organization: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "name"
            | "createdAt"
            | "slug"
            | "logo"
            | "metadata"
          )[];
          readonly destSchema: "organizationsTable";
          readonly cardinality: "one";
        },
      ];
      creator: [
        {
          readonly sourceField: string[];
          readonly destField: (
            | "id"
            | "name"
            | "email"
            | "emailVerified"
            | "image"
            | "createdAt"
            | "updatedAt"
          )[];
          readonly destSchema: "usersTable";
          readonly cardinality: "one";
        },
      ];
    };
  };
};

export const schema = {
  tables: {
    boardsTable: {
      name: "boardsTable",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        color: {
          type: "string",
          optional: true,
          customType: null as unknown,
        },
        slug: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown,
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown,
        },
        deletedAt: {
          type: "number",
          optional: true,
          customType: null as unknown,
        },
        creatorId: {
          type: "string",
          optional: true,
          customType: null as unknown,
          serverName: "creator_id",
        },
        organizationId: {
          type: "string",
          optional: true,
          customType: null as unknown,
          serverName: "organization_id",
        },
      },
      primaryKey: ["id"],
      serverName: "boards",
    },
    columnsTable: {
      name: "columnsTable",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        boardId: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        position: {
          type: "number",
          optional: false,
          customType: null as unknown,
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown,
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown,
        },
        deletedAt: {
          type: "number",
          optional: true,
          customType: null as unknown,
        },
        creatorId: {
          type: "string",
          optional: true,
          customType: null as unknown,
          serverName: "creator_id",
        },
        organizationId: {
          type: "string",
          optional: true,
          customType: null as unknown,
          serverName: "organization_id",
        },
      },
      primaryKey: ["id"],
      serverName: "columns",
    },
    membersTable: {
      name: "membersTable",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        organizationId: {
          type: "string",
          optional: false,
          customType: null as unknown,
          serverName: "organization_id",
        },
        userId: {
          type: "string",
          optional: false,
          customType: null as unknown,
          serverName: "user_id",
        },
        role: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown,
          serverName: "created_at",
        },
      },
      primaryKey: ["id"],
      serverName: "member",
    },
    notesTable: {
      name: "notesTable",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        content: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown,
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown,
        },
        deletedAt: {
          type: "number",
          optional: true,
          customType: null as unknown,
        },
        creatorId: {
          type: "string",
          optional: true,
          customType: null as unknown,
          serverName: "creator_id",
        },
        organizationId: {
          type: "string",
          optional: true,
          customType: null as unknown,
          serverName: "organization_id",
        },
      },
      primaryKey: ["id"],
      serverName: "notes",
    },
    organizationsTable: {
      name: "organizationsTable",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        slug: {
          type: "string",
          optional: true,
          customType: null as unknown,
        },
        logo: {
          type: "string",
          optional: true,
          customType: null as unknown,
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown,
          serverName: "created_at",
        },
        metadata: {
          type: "string",
          optional: true,
          customType: null as unknown,
        },
      },
      primaryKey: ["id"],
      serverName: "organization",
    },
    tasksTable: {
      name: "tasksTable",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        content: {
          type: "string",
          optional: true,
          customType: null as unknown,
        },
        columnId: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        position: {
          type: "number",
          optional: false,
          customType: null as unknown,
        },
        assigneeId: {
          type: "string",
          optional: true,
          customType: null as unknown,
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown,
        },
        updatedAt: {
          type: "number",
          optional: true,
          customType: null as unknown,
        },
        deletedAt: {
          type: "number",
          optional: true,
          customType: null as unknown,
        },
        creatorId: {
          type: "string",
          optional: true,
          customType: null as unknown,
          serverName: "creator_id",
        },
        organizationId: {
          type: "string",
          optional: true,
          customType: null as unknown,
          serverName: "organization_id",
        },
      },
      primaryKey: ["id"],
      serverName: "tasks",
    },
    usersTable: {
      name: "usersTable",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        email: {
          type: "string",
          optional: false,
          customType: null as unknown,
        },
        emailVerified: {
          type: "boolean",
          optional: false,
          customType: null as unknown,
          serverName: "email_verified",
        },
        image: {
          type: "string",
          optional: true,
          customType: null as unknown,
        },
        createdAt: {
          type: "number",
          optional: false,
          customType: null as unknown,
          serverName: "created_at",
        },
        updatedAt: {
          type: "number",
          optional: false,
          customType: null as unknown,
          serverName: "updated_at",
        },
      },
      primaryKey: ["id"],
      serverName: "user",
    },
  },
  relationships: {
    organizationsTable: {
      orgToUsers: [
        {
          sourceField: ["id"],
          destField: ["organizationId"],
          destSchema: "membersTable",
          cardinality: "many",
        },
        {
          sourceField: ["userId"],
          destField: ["id"],
          destSchema: "usersTable",
          cardinality: "many",
        },
      ],
      members: [
        {
          sourceField: ["id"],
          destField: ["organizationId"],
          destSchema: "membersTable",
          cardinality: "many",
        },
      ],
      boards: [
        {
          sourceField: ["id"],
          destField: ["organizationId"],
          destSchema: "boardsTable",
          cardinality: "many",
        },
      ],
      columns: [
        {
          sourceField: ["id"],
          destField: ["organizationId"],
          destSchema: "columnsTable",
          cardinality: "many",
        },
      ],
      tasks: [
        {
          sourceField: ["id"],
          destField: ["organizationId"],
          destSchema: "tasksTable",
          cardinality: "many",
        },
      ],
      notes: [
        {
          sourceField: ["id"],
          destField: ["organizationId"],
          destSchema: "notesTable",
          cardinality: "many",
        },
      ],
    },
    boardsTable: {
      organization: [
        {
          sourceField: ["organizationId"],
          destField: ["id"],
          destSchema: "organizationsTable",
          cardinality: "one",
        },
      ],
      creator: [
        {
          sourceField: ["creatorId"],
          destField: ["id"],
          destSchema: "usersTable",
          cardinality: "one",
        },
      ],
      columns: [
        {
          sourceField: ["id"],
          destField: ["boardId"],
          destSchema: "columnsTable",
          cardinality: "many",
        },
      ],
    },
    columnsTable: {
      board: [
        {
          sourceField: ["boardId"],
          destField: ["id"],
          destSchema: "boardsTable",
          cardinality: "one",
        },
      ],
      organization: [
        {
          sourceField: ["organizationId"],
          destField: ["id"],
          destSchema: "organizationsTable",
          cardinality: "one",
        },
      ],
      creator: [
        {
          sourceField: ["creatorId"],
          destField: ["id"],
          destSchema: "usersTable",
          cardinality: "one",
        },
      ],
      tasks: [
        {
          sourceField: ["id"],
          destField: ["columnId"],
          destSchema: "tasksTable",
          cardinality: "many",
        },
      ],
    },
    membersTable: {
      organization: [
        {
          sourceField: ["organizationId"],
          destField: ["id"],
          destSchema: "organizationsTable",
          cardinality: "one",
        },
      ],
      user: [
        {
          sourceField: ["userId"],
          destField: ["id"],
          destSchema: "usersTable",
          cardinality: "one",
        },
      ],
    },
    notesTable: {
      organization: [
        {
          sourceField: ["organizationId"],
          destField: ["id"],
          destSchema: "organizationsTable",
          cardinality: "one",
        },
      ],
      creator: [
        {
          sourceField: ["creatorId"],
          destField: ["id"],
          destSchema: "usersTable",
          cardinality: "one",
        },
      ],
    },
    tasksTable: {
      column: [
        {
          sourceField: ["columnId"],
          destField: ["id"],
          destSchema: "columnsTable",
          cardinality: "one",
        },
      ],
      organization: [
        {
          sourceField: ["organizationId"],
          destField: ["id"],
          destSchema: "organizationsTable",
          cardinality: "one",
        },
      ],
      creator: [
        {
          sourceField: ["creatorId"],
          destField: ["id"],
          destSchema: "usersTable",
          cardinality: "one",
        },
      ],
      assignee: [
        {
          sourceField: ["assigneeId"],
          destField: ["id"],
          destSchema: "usersTable",
          cardinality: "one",
        },
      ],
    },
    usersTable: {
      members: [
        {
          sourceField: ["id"],
          destField: ["userId"],
          destSchema: "membersTable",
          cardinality: "many",
        },
      ],
      boards: [
        {
          sourceField: ["id"],
          destField: ["creatorId"],
          destSchema: "boardsTable",
          cardinality: "many",
        },
      ],
      columns: [
        {
          sourceField: ["id"],
          destField: ["creatorId"],
          destSchema: "columnsTable",
          cardinality: "many",
        },
      ],
      tasks: [
        {
          sourceField: ["id"],
          destField: ["creatorId"],
          destSchema: "tasksTable",
          cardinality: "many",
        },
      ],
      assignedTasks: [
        {
          sourceField: ["id"],
          destField: ["assigneeId"],
          destSchema: "tasksTable",
          cardinality: "many",
        },
      ],
      notes: [
        {
          sourceField: ["id"],
          destField: ["creatorId"],
          destSchema: "notesTable",
          cardinality: "many",
        },
      ],
    },
  },
} as Schema;
