/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/boards": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": Array<{
              /** Format: uuid */
              id: string;
              name: string;
              color: string | null;
              boardUrl: string;
              tasksCount: number;
              columnsCount: number;
            }>;
          };
        };
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example false */
              success: boolean;
              error: {
                issues: Array<{
                  code: string;
                  path: Array<string | number>;
                  message?: string;
                }>;
                name: string;
              };
              statusCode: number;
            };
          };
        };
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** Format: uuid */
            id: string;
            name: string;
            color?: string | null;
            createdAt?: string | null;
            updatedAt: string | null;
            deletedAt?: string | null;
            boardUrl: string;
          };
        };
      };
      responses: {
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": Record<string, never>;
          };
        };
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example false */
              success: boolean;
              error: {
                issues: Array<{
                  code: string;
                  path: Array<string | number>;
                  message?: string;
                }>;
                name: string;
              };
              statusCode: number;
            };
          };
        };
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/boards/{boardId}/toggle-delete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          boardId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            deleted: boolean;
          };
        };
      };
      responses: {
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              name: string;
              color: string | null;
              boardUrl: string;
            };
          };
        };
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example false */
              success: boolean;
              error: {
                issues: Array<{
                  code: string;
                  path: Array<string | number>;
                  message?: string;
                }>;
                name: string;
              };
              statusCode: number;
            };
          };
        };
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/api/v1/boards/{boardId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          boardId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
            color?: string | null;
            updatedAt: string | null;
            deletedAt?: string | null;
            boardUrl: string;
          };
        };
      };
      responses: {
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": Record<string, never>;
          };
        };
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example false */
              success: boolean;
              error: {
                issues: Array<{
                  code: string;
                  path: Array<string | number>;
                  message?: string;
                }>;
                name: string;
              };
              statusCode: number;
            };
          };
        };
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/api/v1/boards/import": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            boards: Array<{
              boardName: string;
              boardUrl: string;
              columns: Array<{
                name: string;
                position: number;
                tasks: Array<{
                  /** Format: uuid */
                  columnId: string;
                  name: string;
                  position: number;
                }>;
              }>;
            }>;
          };
        };
      };
      responses: {
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": Record<string, never>;
          };
        };
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example false */
              success: boolean;
              error: {
                issues: Array<{
                  code: string;
                  path: Array<string | number>;
                  message?: string;
                }>;
                name: string;
              };
              statusCode: number;
            };
          };
        };
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/columns": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query: {
          boardUrl: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              boardId: string;
              boardName: string;
              columns: Array<{
                /** Format: uuid */
                id: string;
                name: string;
                /** Format: uuid */
                boardId: string;
                position: number;
              }>;
              tasks: Array<{
                /** Format: uuid */
                id: string;
                name: string;
                /** Format: uuid */
                columnId: string;
                position: number;
              }>;
            };
          };
        };
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example false */
              success: boolean;
              error: {
                issues: Array<{
                  code: string;
                  path: Array<string | number>;
                  message?: string;
                }>;
                name: string;
              };
              statusCode: number;
            };
          };
        };
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            boardId: string;
            position: number;
            createdAt?: string | null;
            updatedAt: string | null;
          };
        };
      };
      responses: {
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": Record<string, never>;
          };
        };
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example false */
              success: boolean;
              error: {
                issues: Array<{
                  code: string;
                  path: Array<string | number>;
                  message?: string;
                }>;
                name: string;
              };
              statusCode: number;
            };
          };
        };
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/columns/reorder": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": Array<{
            /** Format: uuid */
            id: string;
            position: number;
          }>;
        };
      };
      responses: {
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": Record<string, never>;
          };
        };
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example false */
              success: boolean;
              error: {
                issues: Array<{
                  code: string;
                  path: Array<string | number>;
                  message?: string;
                }>;
                name: string;
              };
              statusCode: number;
            };
          };
        };
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/api/v1/columns/{columnId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          columnId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": Record<string, never>;
          };
        };
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example false */
              success: boolean;
              error: {
                issues: Array<{
                  code: string;
                  path: Array<string | number>;
                  message?: string;
                }>;
                name: string;
              };
              statusCode: number;
            };
          };
        };
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          columnId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
          };
        };
      };
      responses: {
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              name: string;
            };
          };
        };
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example false */
              success: boolean;
              error: {
                issues: Array<{
                  code: string;
                  path: Array<string | number>;
                  message?: string;
                }>;
                name: string;
              };
              statusCode: number;
            };
          };
        };
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/api/v1/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": Array<{
            position: number;
            /** Format: uuid */
            columnId: string;
            /** Format: uuid */
            id: string;
          }>;
        };
      };
      responses: {
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": Record<string, never>;
          };
        };
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example false */
              success: boolean;
              error: {
                issues: Array<{
                  code: string;
                  path: Array<string | number>;
                  message?: string;
                }>;
                name: string;
              };
              statusCode: number;
            };
          };
        };
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
      };
    };
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            columnId: string;
            position: number;
            createdAt: string | null;
            updatedAt: string | null;
            deletedAt?: string | null;
          };
        };
      };
      responses: {
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": Record<string, never>;
          };
        };
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example false */
              success: boolean;
              error: {
                issues: Array<{
                  code: string;
                  path: Array<string | number>;
                  message?: string;
                }>;
                name: string;
              };
              statusCode: number;
            };
          };
        };
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tasks/{taskId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          taskId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              name: string;
              /** Format: uuid */
              columnId: string;
              position: number;
              createdAt: string | null;
              updatedAt: string | null;
              deletedAt: string | null;
              content: string | null;
            };
          };
        };
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example false */
              success: boolean;
              error: {
                issues: Array<{
                  code: string;
                  path: Array<string | number>;
                  message?: string;
                }>;
                name: string;
              };
              statusCode: number;
            };
          };
        };
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          taskId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": Record<string, never>;
          };
        };
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example false */
              success: boolean;
              error: {
                issues: Array<{
                  code: string;
                  path: Array<string | number>;
                  message?: string;
                }>;
                name: string;
              };
              statusCode: number;
            };
          };
        };
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          taskId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            name?: string;
            content?: string | null;
            updatedAt: string;
          };
        };
      };
      responses: {
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": Record<string, never>;
          };
        };
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example false */
              success: boolean;
              error: {
                issues: Array<{
                  code: string;
                  path: Array<string | number>;
                  message?: string;
                }>;
                name: string;
              };
              statusCode: number;
            };
          };
        };
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
      };
    };
    trace?: never;
  };
  "/api/v1/storage/user-image-presigned-url": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            fileName: string;
            contentType: string;
          };
        };
      };
      responses: {
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              url: string;
              key: string;
              imageUrl: string;
            };
          };
        };
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example false */
              success: boolean;
              error: {
                issues: Array<{
                  code: string;
                  path: Array<string | number>;
                  message?: string;
                }>;
                name: string;
              };
              statusCode: number;
            };
          };
        };
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/notes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              notes: Array<{
                /** Format: uuid */
                id: string;
                name: string;
                updatedAt: string | null;
              }>;
            };
          };
        };
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example false */
              success: boolean;
              error: {
                issues: Array<{
                  code: string;
                  path: Array<string | number>;
                  message?: string;
                }>;
                name: string;
              };
              statusCode: number;
            };
          };
        };
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
            content: string;
            createdAt?: string | null;
            /** Format: uuid */
            id: string;
          };
        };
      };
      responses: {
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              name: string;
              content: string;
              createdAt: string | null;
              updatedAt: string | null;
              deletedAt: string | null;
              organizationId: string;
            };
          };
        };
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example false */
              success: boolean;
              error: {
                issues: Array<{
                  code: string;
                  path: Array<string | number>;
                  message?: string;
                }>;
                name: string;
              };
              statusCode: number;
            };
          };
        };
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/notes/{noteId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          noteId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              name: string;
              content: string;
              createdAt: string | null;
              updatedAt: string | null;
              deletedAt: string | null;
              organizationId: string;
            };
          };
        };
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example false */
              success: boolean;
              error: {
                issues: Array<{
                  code: string;
                  path: Array<string | number>;
                  message?: string;
                }>;
                name: string;
              };
              statusCode: number;
            };
          };
        };
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          noteId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": {
            content: string;
            updatedAt: string | null;
            name: string;
          };
        };
      };
      responses: {
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              name: string;
              content: string;
              createdAt: string | null;
              updatedAt: string | null;
              deletedAt: string | null;
              organizationId: string;
            };
          };
        };
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example false */
              success: boolean;
              error: {
                issues: Array<{
                  code: string;
                  path: Array<string | number>;
                  message?: string;
                }>;
                name: string;
              };
              statusCode: number;
            };
          };
        };
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              message: string;
              statusCode: number;
            };
          };
        };
      };
    };
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
