import createClient, { Middleware } from "openapi-fetch";
import type { paths } from "@/types/api-schema"; // generated by openapi-typescript
import { routeMap } from "@/lib/constants";

export const fetchClient = createClient<paths>({
  baseUrl: import.meta.env.CLIENT_MY_API_BASE_URL,
  credentials: 'include'
});

const authMiddleware: Middleware = {
  async onResponse({ response, }) {
    if (response.status === 401) {
      if (typeof window === 'undefined' || window.location.pathname.includes(routeMap.login)) return;
      window.location.href = routeMap.login;
    }


  },
};

fetchClient.use(authMiddleware);
