import createClient from "openapi-fetch";
import type { paths } from "@/types/api-schema"; // generated by openapi-typescript

export const fetchClient = createClient<paths>({
  baseUrl: import.meta.env.CLIENT_MY_API_BASE_URL,
  credentials: 'include'
});

// const errorMiddleware: Middleware = {
//   async onResponse({ response, }) {
//     // Throw on error so that Tanstack query can catch it.
//     if (!response.ok) {
//       throw new Error(`${response.url}: ${response.status} ${response.statusText}`)
//     }
//   },
// };

// fetchClient.use(errorMiddleware);
