import createClient from "openapi-fetch";
import type { paths } from "@/types/api-schema"; // generated by openapi-typescript
import type { paths as authPaths } from "@/types/api-auth-schema"; // generated by openapi-typescript
export const fetchClient = createClient<paths>({
  baseUrl: import.meta.env.CLIENT_MY_API_BASE_URL,
  credentials: 'include'
});


export const fetchAuthClient = createClient<authPaths>({
  baseUrl: `${import.meta.env.CLIENT_MY_API_BASE_URL}/api/v1/auth`,
  credentials: "include",
});
