import createClient, { Middleware } from "openapi-fetch";
import type { paths } from "@/types/api-schema"; // generated by openapi-typescript
import { promiseTimeout } from "@/lib/utils";

export const fetchClient = createClient<paths>({
  baseUrl: import.meta.env.CLIENT_MY_API_BASE_URL,
  credentials: "include",
});

if (import.meta.env.DEV) {
  const delayMiddleware: Middleware = {
    async onRequest({ request }) {
      await promiseTimeout(500);
      return request;
    },
  };

  fetchClient.use(delayMiddleware);
}
