import createClient, { type Middleware } from "openapi-fetch";
import type { paths } from "@/types/api-schema"; // generated by openapi-typescript
import { routeMap } from "@/lib/constants";

export const fetchClient = createClient<paths>({
  baseUrl: process.env.NEXT_PUBLIC_API_URL,
  credentials: "include",
});

const authMiddleware: Middleware = {
  async onResponse({ response, }) {
    if (response.status === 401) {
      window.location.href = routeMap.login
      return;
    }
    return undefined;
  },
};

fetchClient.use(authMiddleware);
